import { useEffect, useState, type FormEvent } from 'react'
import { api } from '@/api/client'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { clearSpanishValidationMessage, setSpanishValidationMessage } from '@/lib/formValidation'
interface Announcement { id: string; title: string; body: string; publishedAt: string | null }
export function AnnouncementsPage() {
  const [items, setItems] = useState<Announcement[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modalOpen, setModalOpen] = useState(false)
  const load = () => api<Announcement[]>('/announcements').then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api('/announcements', { method: 'POST', body: JSON.stringify({ title: data.get('title'), body: data.get('body'), published: data.get('published') === 'on' }) }); form.reset(); setModalOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible publicar el anuncio.') } }
  async function setPublished(item: Announcement, published: boolean) { await api(`/announcements/${item.id}`, { method: 'PATCH', body: JSON.stringify({ published }) }); await load() }
  return <><PageHeader title="Cartelera digital" description="Redacte y publique anuncios de texto para los residentes." action={<Button onClick={() => setModalOpen(true)}>Crear anuncio</Button>} />{error && <ErrorState message={error} />}
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Crear anuncio" description="Escriba el mensaje que desea compartir con los residentes."><form onSubmit={create} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="space-y-3"><label className="grid gap-1 text-sm font-medium">Título del anuncio<input name="title" required maxLength={160} placeholder="Ej. Mantenimiento del ascensor" className="w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Mensaje<textarea name="body" required rows={5} placeholder="Ej. El ascensor estará fuera de servicio el sábado..." className="w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="flex items-center gap-2 text-sm"><input name="published" type="checkbox" />Publicar inmediatamente</label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => setModalOpen(false)}>Cancelar</Button><Button type="submit">Crear anuncio</Button></div></form></Modal>
    {loading ? <LoadingState /> : items.length === 0 ? <EmptyState>Todavía no hay anuncios.</EmptyState> : <div className="grid gap-4">{items.map((item) => <article key={item.id} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{item.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.body}</p></div><span className="shrink-0 rounded-full bg-muted px-2 py-1 text-xs">{item.publishedAt ? 'Publicado' : 'Borrador'}</span></div><Button className="mt-4" variant="outline" size="sm" onClick={() => void setPublished(item, !item.publishedAt)}>{item.publishedAt ? 'Retirar publicación' : 'Publicar'}</Button></article>)}</div>}
  </>
}
