import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Archive, Edit, Filter, Megaphone, Plus, Search, X } from 'lucide-react'
import { api } from '@/api/client'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { Pagination } from '@/components/Pagination'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { clearSpanishValidationMessage, setSpanishValidationMessage } from '@/lib/formValidation'
interface Announcement { id: string; title: string; body: string; status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'; publishedAt: string | null; updatedAt?: string; author?: { name: string; email: string } }
export function AnnouncementsPage() {
  const [items, setItems] = useState<Announcement[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState<Announcement | null>(null); const [pendingPublication, setPendingPublication] = useState<{ item: Announcement; published: boolean } | null>(null); const [publicationBusy, setPublicationBusy] = useState(false); const [createBusy, setCreateBusy] = useState(false); const [editBusy, setEditBusy] = useState(false); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('ALL'); const [page, setPage] = useState(1)
  const load = () => api<Announcement[]>('/announcements').then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setCreateBusy(true); try { await api('/announcements', { method: 'POST', body: JSON.stringify({ title: data.get('title'), body: data.get('body'), published: data.get('published') === 'on' }) }); form.reset(); setModalOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible publicar el anuncio.') } finally { setCreateBusy(false) } }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); setEditBusy(true); setError(''); try { await api(`/announcements/${editing.id}`, { method: 'PATCH', body: JSON.stringify({ title: data.get('title'), body: data.get('body') }) }); setEditing(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible editar el anuncio.') } finally { setEditBusy(false) } }
  async function setPublished(item: Announcement, published: boolean) { setPublicationBusy(true); setError(''); try { await api(`/announcements/${item.id}`, { method: 'PATCH', body: JSON.stringify({ published }) }); setPendingPublication(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible actualizar el anuncio.') } finally { setPublicationBusy(false) } }
  const filteredItems = useMemo(() => items.filter((item) => { const normalizedQuery = query.trim().toLocaleLowerCase(); const matchesQuery = !normalizedQuery || item.title.toLocaleLowerCase().includes(normalizedQuery) || item.body.toLocaleLowerCase().includes(normalizedQuery); const isPublished = item.status ? item.status === 'PUBLISHED' : Boolean(item.publishedAt); const matchesStatus = statusFilter === 'ALL' || (statusFilter === 'PUBLISHED' ? isPublished : !isPublished); return matchesQuery && matchesStatus }), [items, query, statusFilter])
  const pageSize = 10; const pageCount = Math.max(1, Math.ceil(filteredItems.length / pageSize)); const paginatedItems = filteredItems.slice((page - 1) * pageSize, page * pageSize)
  return <><PageHeader title="Cartelera digital" description="Redacte y publique anuncios de texto para los residentes." action={<Button onClick={() => setModalOpen(true)}><Plus className="size-4" />Crear anuncio</Button>} />{error && <ErrorState message={error} />}
    <section className="mb-6 rounded-xl border bg-card p-4" aria-label="Filtros de anuncios"><div className="mb-3 flex items-center gap-2 text-sm font-medium"><Filter className="size-4" />Buscar y filtrar anuncios</div><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px]"><label className="relative"><span className="sr-only">Buscar en anuncios</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Ej. mantenimiento o ascensor" className="w-full rounded-lg border bg-background py-2 pl-9 pr-3" /></label><label><span className="sr-only">Filtrar por estado</span><select value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1) }} className="w-full cursor-pointer rounded-lg border bg-background px-3 py-2"><option value="ALL">Todos los estados</option><option value="PUBLISHED">Publicados</option><option value="DRAFT">Borradores</option></select></label></div></section>
    <Modal open={modalOpen} onClose={() => { if (!createBusy) setModalOpen(false) }} title="Crear anuncio" description="Complete los campos obligatorios. Marque la opción de publicación solo si desea mostrarlo inmediatamente."><form onSubmit={create} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="space-y-3"><label className="grid gap-1 text-sm font-medium">Título del anuncio <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="title" required minLength={5} maxLength={160} placeholder="Ej. Mantenimiento del ascensor" className="w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Mensaje <span className="font-normal text-muted-foreground">(obligatorio)</span><textarea name="body" required minLength={10} maxLength={2000} rows={5} placeholder="Ej. El ascensor estará fuera de servicio el sábado..." className="w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="flex items-center gap-2 text-sm"><input name="published" type="checkbox" />Publicar inmediatamente <span className="text-muted-foreground">(opcional)</span></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" disabled={createBusy} onClick={() => setModalOpen(false)}><X className="size-4" />Cancelar</Button><Button type="submit" disabled={createBusy}><Plus className="size-4" />{createBusy ? 'Creando…' : 'Crear anuncio'}</Button></div></form></Modal>
    <Modal open={Boolean(editing)} onClose={() => { if (!editBusy) setEditing(null) }} title="Editar anuncio" description="Actualice el título y el contenido del comunicado. El estado de publicación se gestiona mediante una confirmación separada."><form onSubmit={update} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="space-y-3"><label className="grid gap-1 text-sm font-medium">Título del anuncio <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="title" required minLength={5} maxLength={160} defaultValue={editing?.title} className="w-full rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Mensaje <span className="font-normal text-muted-foreground">(obligatorio)</span><textarea name="body" required minLength={10} maxLength={2000} rows={5} defaultValue={editing?.body} className="w-full rounded-lg border px-3 py-2 font-normal" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" disabled={editBusy} onClick={() => setEditing(null)}><X className="size-4" />Cancelar</Button><Button type="submit" disabled={editBusy}><Edit className="size-4" />{editBusy ? 'Guardando…' : 'Guardar cambios'}</Button></div></form></Modal>
    {loading ? <LoadingState /> : filteredItems.length === 0 ? <EmptyState>{items.length === 0 ? 'Todavía no hay anuncios.' : 'No hay anuncios que coincidan con los filtros seleccionados.'}</EmptyState> : <><div className="grid gap-4">{paginatedItems.map((item) => { const isPublished = item.status ? item.status === 'PUBLISHED' : Boolean(item.publishedAt); return <article key={item.id} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{item.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.body}</p><p className="mt-3 text-xs text-muted-foreground">{item.author ? `Publicado por ${item.author.name}` : 'Autor no disponible'}{item.updatedAt ? ` · Actualizado ${new Date(item.updatedAt).toLocaleDateString('es')}` : ''}</p></div><span className="shrink-0 rounded-full bg-muted px-2 py-1 text-xs">{isPublished ? 'Publicado' : 'Borrador'}</span></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" size="sm" title="Editar anuncio" aria-label="Editar anuncio" onClick={() => setEditing(item)}><Edit className="size-4" /><span className="hidden sm:inline">Editar</span></Button><Button variant="outline" size="sm" title={isPublished ? 'Retirar publicación' : 'Publicar anuncio'} aria-label={isPublished ? 'Retirar publicación' : 'Publicar anuncio'} onClick={() => setPendingPublication({ item, published: !isPublished })}>{isPublished ? <><Archive className="size-4" /><span className="hidden sm:inline">Retirar publicación</span></> : <><Megaphone className="size-4" /><span className="hidden sm:inline">Publicar</span></>}</Button></div></article> })}</div><Pagination page={page} pageCount={pageCount} total={filteredItems.length} pageSize={pageSize} onPageChange={setPage} /></>}
    <ConfirmDialog open={Boolean(pendingPublication)} onCancel={() => setPendingPublication(null)} onConfirm={() => { if (pendingPublication) void setPublished(pendingPublication.item, pendingPublication.published) }} busy={publicationBusy} title={pendingPublication?.published ? 'Publicar anuncio' : 'Retirar publicación'} description={pendingPublication ? `¿Desea ${pendingPublication.published ? 'publicar' : 'retirar'} el anuncio “${pendingPublication.item.title}”?` : ''} confirmLabel={pendingPublication?.published ? 'Publicar anuncio' : 'Retirar publicación'} destructive={pendingPublication ? !pendingPublication.published : false} />
  </>
}
