import { useEffect, useState, type FormEvent } from 'react'
import { api } from '@/api/client'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { clearSpanishValidationMessage, setSpanishValidationMessage } from '@/lib/formValidation'
interface Unit { id: string; code: string; active: boolean }
interface Resident { id: string; name: string; phone: string | null; active: boolean; unit: Unit }
export function ResidentsPage() {
  const [items, setItems] = useState<Resident[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modalOpen, setModalOpen] = useState(false)
  const load = () => Promise.all([api<Resident[]>('/residents'), api<Unit[]>('/units')]).then(([residents, unitList]) => { setItems(residents); setUnits(unitList) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api('/residents', { method: 'POST', body: JSON.stringify(Object.fromEntries(data)) }); form.reset(); setModalOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible crear el residente.') } }
  async function revoke(item: Resident) { await api(`/residents/${item.id}`, { method: 'PATCH', body: JSON.stringify({ active: false }) }); await load() }
  return <><PageHeader title="Residentes" description="Cree cuentas de residentes y revoque su acceso cuando sea necesario." action={<Button onClick={() => setModalOpen(true)}>Agregar residente</Button>} />{error && <ErrorState message={error} />}
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Agregar residente" description="Complete los datos de acceso y asigne una unidad residencial."><form onSubmit={create} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Nombre completo<input name="name" required autoComplete="name" placeholder="Ej. Ana García" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Correo electrónico<input name="email" required type="email" autoComplete="email" placeholder="ana.garcia@correo.com" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Teléfono <span className="font-normal text-muted-foreground">(opcional)</span><input name="phone" autoComplete="tel" placeholder="Ej. +593 300 123 4567" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Unidad residencial<select name="unitId" required className="cursor-pointer rounded-lg border bg-background px-3 py-2 font-normal"><option value="">Seleccione</option>{units.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Contraseña temporal<input name="password" required type="password" minLength={8} autoComplete="new-password" placeholder="Mínimo 8 caracteres" className="rounded-lg border px-3 py-2 font-normal" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => setModalOpen(false)}>Cancelar</Button><Button type="submit">Crear residente</Button></div></form></Modal>
    {loading ? <LoadingState /> : items.length === 0 ? <EmptyState>Todavía no hay residentes.</EmptyState> : <div className="grid gap-3">{items.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-4"><div><h2 className="font-medium">{item.name}</h2><p className="text-sm text-muted-foreground">Unidad {item.unit.code}{item.phone ? ` · ${item.phone}` : ''}</p></div><div className="flex items-center gap-3"><span className="text-sm">{item.active ? 'Activo' : 'Revocado'}</span>{item.active && <Button variant="outline" size="sm" onClick={() => void revoke(item)}>Revocar acceso</Button>}</div></article>)}</div>}
  </>
}
