import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Edit, Filter, Plus, RotateCcw, Search, UserRoundX, X } from 'lucide-react'
import { api } from '@/api/client'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { Pagination } from '@/components/Pagination'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { clearSpanishValidationMessage, setSpanishValidationMessage } from '@/lib/formValidation'
interface Unit { id: string; code: string; active: boolean }
interface Resident { id: string; name: string; email?: string; phone: string | null; active: boolean; unit: Unit }
export function ResidentsPage() {
  const [items, setItems] = useState<Resident[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState<Resident | null>(null); const [pendingAccess, setPendingAccess] = useState<{ item: Resident; active: boolean } | null>(null); const [accessBusy, setAccessBusy] = useState(false); const [createBusy, setCreateBusy] = useState(false); const [editBusy, setEditBusy] = useState(false); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('ALL'); const [unitFilter, setUnitFilter] = useState('ALL'); const [page, setPage] = useState(1)
  const load = () => Promise.all([api<Resident[]>('/residents'), api<Unit[]>('/units')]).then(([residents, unitList]) => { setItems(residents); setUnits(unitList) }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setCreateBusy(true); try { await api('/residents', { method: 'POST', body: JSON.stringify(Object.fromEntries(data)) }); form.reset(); setModalOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible crear el residente.') } finally { setCreateBusy(false) } }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); setEditBusy(true); try { await api(`/residents/${editing.id}`, { method: 'PATCH', body: JSON.stringify({ name: data.get('name'), phone: data.get('phone'), unitId: data.get('unitId') }) }); setEditing(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible actualizar el residente.') } finally { setEditBusy(false) } }
  async function setAccess(item: Resident, active: boolean) { setAccessBusy(true); setError(''); try { await api(`/residents/${item.id}`, { method: 'PATCH', body: JSON.stringify({ active }) }); setPendingAccess(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible actualizar el acceso.') } finally { setAccessBusy(false) } }
  const filteredItems = useMemo(() => items.filter((item) => { const normalizedQuery = query.trim().toLocaleLowerCase(); const matchesQuery = !normalizedQuery || item.name.toLocaleLowerCase().includes(normalizedQuery) || item.email?.toLocaleLowerCase().includes(normalizedQuery) || item.unit.code.toLocaleLowerCase().includes(normalizedQuery); const matchesStatus = statusFilter === 'ALL' || (statusFilter === 'ACTIVE' ? item.active : !item.active); const matchesUnit = unitFilter === 'ALL' || item.unit.id === unitFilter; return matchesQuery && matchesStatus && matchesUnit }), [items, query, statusFilter, unitFilter])
  const pageSize = 10; const pageCount = Math.max(1, Math.ceil(filteredItems.length / pageSize)); const paginatedItems = filteredItems.slice((page - 1) * pageSize, page * pageSize)
  return <><PageHeader title="Residentes" description="Gestione las cuentas, unidades asignadas y permisos de acceso." action={<Button onClick={() => setModalOpen(true)}><Plus className="size-4" />Agregar residente</Button>} />{error && <ErrorState message={error} />}
    <section className="mb-6 rounded-xl border bg-card p-4" aria-label="Filtros de residentes"><div className="mb-3 flex items-center gap-2 text-sm font-medium"><Filter className="size-4" />Buscar y filtrar residentes</div><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px_220px]"><label className="relative"><span className="sr-only">Buscar por nombre o unidad</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Ej. Ana García o Torre A-101" className="w-full rounded-lg border bg-background py-2 pl-9 pr-3" /></label><label><span className="sr-only">Filtrar por estado</span><select value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1) }} className="w-full cursor-pointer rounded-lg border bg-background px-3 py-2"><option value="ALL">Todos los estados</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Revocados</option></select></label><label><span className="sr-only">Filtrar por unidad</span><select value={unitFilter} onChange={(event) => { setUnitFilter(event.target.value); setPage(1) }} className="w-full cursor-pointer rounded-lg border bg-background px-3 py-2"><option value="ALL">Todas las unidades</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.code}</option>)}</select></label></div></section>
    <Modal open={modalOpen} onClose={() => { if (!createBusy) setModalOpen(false) }} title="Agregar residente" description="Complete los campos obligatorios. Los campos marcados como opcionales pueden dejarse vacíos."><form onSubmit={create} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Nombre completo <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="name" required minLength={3} maxLength={100} pattern="[A-Za-zÁÉÍÓÚáéíóúÑñÜü ]+" autoComplete="name" placeholder="Ej. Ana García" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Correo electrónico <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="email" required type="email" maxLength={120} autoComplete="email" placeholder="ana.garcia@correo.com" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Teléfono <span className="font-normal text-muted-foreground">(opcional)</span><input name="phone" pattern="[+0-9 ()-]{7,20}" autoComplete="tel" placeholder="Ej. +593 300 123 4567" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Unidad residencial <span className="font-normal text-muted-foreground">(obligatorio)</span><select name="unitId" required className="cursor-pointer rounded-lg border bg-background px-3 py-2 font-normal"><option value="">Seleccione una unidad</option>{units.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Contraseña temporal <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="password" required type="password" minLength={8} maxLength={72} autoComplete="new-password" placeholder="Mínimo 8 caracteres" className="rounded-lg border px-3 py-2 font-normal" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" disabled={createBusy} onClick={() => setModalOpen(false)}><X className="size-4" />Cancelar</Button><Button type="submit" disabled={createBusy}><Plus className="size-4" />{createBusy ? 'Creando…' : 'Crear residente'}</Button></div></form></Modal>
    <Modal open={Boolean(editing)} onClose={() => { if (!editBusy) setEditing(null) }} title="Editar residente" description="Actualice los datos administrativos del residente. El correo y la contraseña se gestionan mediante seguridad de cuenta."><form onSubmit={update} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Nombre completo <span className="font-normal text-muted-foreground">(obligatorio)</span><input name="name" required minLength={3} maxLength={100} defaultValue={editing?.name} className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Teléfono <span className="font-normal text-muted-foreground">(opcional)</span><input name="phone" pattern="[+0-9 ()-]{7,20}" defaultValue={editing?.phone ?? ''} placeholder="Ej. +593 300 123 4567" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Unidad residencial <span className="font-normal text-muted-foreground">(obligatorio)</span><select name="unitId" required defaultValue={editing?.unit.id} className="cursor-pointer rounded-lg border bg-background px-3 py-2"><option value="">Seleccione una unidad</option>{units.filter((x) => x.active || x.id === editing?.unit.id).map((x) => <option key={x.id} value={x.id}>{x.code}</option>)}</select></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" disabled={editBusy} onClick={() => setEditing(null)}><X className="size-4" />Cancelar</Button><Button type="submit" disabled={editBusy}><Edit className="size-4" />{editBusy ? 'Guardando…' : 'Guardar cambios'}</Button></div></form></Modal>
    {loading ? <LoadingState /> : filteredItems.length === 0 ? <EmptyState>{items.length === 0 ? 'Todavía no hay residentes.' : 'No hay residentes que coincidan con los filtros seleccionados.'}</EmptyState> : <><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-3">Residente</th><th className="p-3">Unidad</th><th className="p-3">Teléfono</th><th className="p-3">Estado</th><th className="p-3 text-right"><span className="sr-only">Acciones</span></th></tr></thead><tbody>{paginatedItems.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-3 font-medium">{item.name}</td><td className="p-3">{item.unit.code}</td><td className="p-3">{item.phone || 'No registrado'}</td><td className="p-3">{item.active ? 'Activo' : 'Revocado'}</td><td className="flex justify-end gap-2 p-3"><Button variant="outline" size="sm" aria-label={`Editar a ${item.name}`} onClick={() => setEditing(item)}><Edit className="size-4" />Editar</Button>{item.active ? <Button variant="outline" size="sm" onClick={() => setPendingAccess({ item, active: false })}><UserRoundX className="size-4" />Revocar acceso</Button> : <Button variant="outline" size="sm" onClick={() => setPendingAccess({ item, active: true })}><RotateCcw className="size-4" />Activar acceso</Button>}</td></tr>)}</tbody></table></div><Pagination page={page} pageCount={pageCount} total={filteredItems.length} pageSize={pageSize} onPageChange={setPage} /></>}
    <ConfirmDialog open={Boolean(pendingAccess)} onCancel={() => setPendingAccess(null)} onConfirm={() => { if (pendingAccess) void setAccess(pendingAccess.item, pendingAccess.active) }} busy={accessBusy} title={pendingAccess?.active ? 'Activar acceso' : 'Revocar acceso'} description={pendingAccess ? `¿Desea ${pendingAccess.active ? 'activar nuevamente' : 'revocar'} el acceso de ${pendingAccess.item.name}?` : ''} confirmLabel={pendingAccess?.active ? 'Activar acceso' : 'Revocar acceso'} destructive={pendingAccess ? !pendingAccess.active : false} />
  </>
}
