import { useEffect, useMemo, useState } from 'react'
import { Filter, Search } from 'lucide-react'
import { api } from '@/api/client'
import { Pagination } from '@/components/Pagination'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
interface Ticket { id: string; description: string; status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED'; createdAt: string }
export function TicketsPage() {
  const [items, setItems] = useState<Ticket[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('ALL'); const [page, setPage] = useState(1)
  const load = () => api<Ticket[]>('/tickets').then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); useEffect(() => { void load() }, [])
  async function update(item: Ticket, status: Ticket['status']) { try { await api(`/tickets/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible actualizar la incidencia.') } }
  const filteredItems = useMemo(() => items.filter((item) => { const matchesQuery = !query.trim() || item.description.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()); const matchesStatus = statusFilter === 'ALL' || item.status === statusFilter; return matchesQuery && matchesStatus }), [items, query, statusFilter])
  const pageSize = 10; const pageCount = Math.max(1, Math.ceil(filteredItems.length / pageSize)); const paginatedItems = filteredItems.slice((page - 1) * pageSize, page * pageSize)
  return <><PageHeader title="Incidencias de mantenimiento" description="Revise las incidencias de los residentes y supervise su estado de resolución." />{error && <ErrorState message={error} />}<section className="mb-6 rounded-xl border bg-card p-4" aria-label="Filtros de incidencias"><div className="mb-3 flex items-center gap-2 text-sm font-medium"><Filter className="size-4" />Buscar y filtrar incidencias</div><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px]"><label className="relative"><span className="sr-only">Buscar incidencia</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Ej. Fuga de agua o ascensor" className="w-full rounded-lg border bg-background py-2 pl-9 pr-3" /></label><label><span className="sr-only">Filtrar por estado</span><select value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1) }} className="w-full cursor-pointer rounded-lg border bg-background px-3 py-2"><option value="ALL">Todos los estados</option><option value="OPEN">Abiertas</option><option value="IN_PROGRESS">En curso</option><option value="RESOLVED">Resueltas</option></select></label></div></section>{loading ? <LoadingState /> : filteredItems.length === 0 ? <EmptyState>{items.length === 0 ? 'No se han registrado incidencias de mantenimiento.' : 'No hay incidencias que coincidan con los filtros seleccionados.'}</EmptyState> : <><div className="grid gap-3">{paginatedItems.map((item) => <article key={item.id} className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{item.description}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString('es')}</p></div><select aria-label="Estado de la incidencia" className="cursor-pointer rounded-lg border bg-background px-3 py-2 text-sm" value={item.status} onChange={(e) => void update(item, e.target.value as Ticket['status'])}><option value="OPEN">Abierta</option><option value="IN_PROGRESS">En curso</option><option value="RESOLVED">Resuelta</option></select></div></article>)}</div><Pagination page={page} pageCount={pageCount} total={filteredItems.length} pageSize={pageSize} onPageChange={setPage} /></> }</>
}
