import { useEffect, useState, type FormEvent } from 'react'
import { api } from '@/api/client'
import { EmptyState, ErrorState, LoadingState, PageHeader } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/ui/modal'
import { clearSpanishValidationMessage, setSpanishValidationMessage } from '@/lib/formValidation'
interface Unit { id: string; code: string; address: string; parkingSpaces: number; active: boolean }
export function UnitsPage() {
  const [items, setItems] = useState<Unit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modalOpen, setModalOpen] = useState(false)
  const load = () => api<Unit[]>('/units').then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setError(''); try { await api('/units', { method: 'POST', body: JSON.stringify({ code: data.get('code'), address: data.get('address'), parkingSpaces: Number(data.get('parkingSpaces')) }) }); form.reset(); setModalOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible crear la unidad.') } }
  async function toggle(item: Unit) { await api(`/units/${item.id}`, { method: 'PATCH', body: JSON.stringify({ active: !item.active }) }); await load() }
  return <><PageHeader title="Unidades residenciales" description="Gestione las direcciones, la capacidad de estacionamiento y el estado de acceso de las unidades." action={<Button onClick={() => setModalOpen(true)}>Agregar unidad</Button>} />{error && <ErrorState message={error} />}
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Agregar unidad" description="Registre una nueva unidad residencial y su capacidad de estacionamiento."><form onSubmit={create} onInvalid={setSpanishValidationMessage} onInput={clearSpanishValidationMessage} className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Código de unidad<input name="code" required placeholder="Ej. Torre A-101" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Dirección<input name="address" required autoComplete="street-address" placeholder="Ej. Calle 10 # 20-30" className="rounded-lg border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-medium">Plazas de estacionamiento<input name="parkingSpaces" required type="number" min="0" inputMode="numeric" placeholder="Ej. 2" className="rounded-lg border px-3 py-2 font-normal" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => setModalOpen(false)}>Cancelar</Button><Button type="submit">Crear unidad</Button></div></form></Modal>
    {loading ? <LoadingState /> : items.length === 0 ? <EmptyState>Todavía no hay unidades residenciales.</EmptyState> : <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="p-3">Código</th><th className="p-3">Dirección</th><th className="p-3">Estacionamiento</th><th className="p-3">Estado</th><th className="p-3"><span className="sr-only">Acciones</span></th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-3 font-medium">{item.code}</td><td className="p-3">{item.address}</td><td className="p-3">{item.parkingSpaces.toLocaleString('es')}</td><td className="p-3">{item.active ? 'Activa' : 'Inactiva'}</td><td className="p-3 text-right"><Button variant="outline" size="sm" onClick={() => void toggle(item)}>{item.active ? 'Desactivar' : 'Activar'}</Button></td></tr>)}</tbody></table></div>}
  </>
}
